### PR TITLE
Timesync in the main loop

### PR DESCRIPTION
**Pull request by mateumann**
Adds a skeleton for time synchronisation mechanism.

A scheduler step `scTIMESYNC` is added in `CNodeGenerator` which is then used in `CNodeGenerator::flush_file_realtime` method to call `do_timesync` function, according to CGlobalInfo::m_options.m_timesync_period` and `CGlobalInfo::m_options.m_timesync_method`.

Time synchronisation methods would be implemented in `src/utils/utl_timesync.cpp` (as is `do_timesync`).

### CODE REVIEW

**Comment by mateumann** [comment]
I have added a client (Rx) side for the communication.  I will explain more if need be in a few days.

**Comment by hhaim** [comment]
Hi @mateumann 
You definitely brave, touching the heart of the scheduler. 
I would look for a way **not** to touch it as it is influence all the modes and it is super sensitive to performance  ```CNodeGenerator::flush_file_realtime(dsec_t max_time,```

You just need to sync the latency timer not the TRex scheduler, timer --> why do you need to sync them both? 

My suggestion is to create a event (using a new node) for time sync -- this node will work only if it was asked. The writer (Tx side) will use the diff + highres tick for writing the time diff 
The Rx is not in critical path so there is no issue there 

The rest of the TX scheduler will work the same

**Comment by hhaim** [comment]
@mateumann looks better now. The code is in the right place now  (debug print should be removed)
Don't you want the high res-timer counter to be per  DP core? Currently, all the DP syncs the **same** shared counter ```dsec_t do_timesync(dsec_t cur_time)  -does nothing``` this should be timer sync per thread 

2. the latency stream (tx side) should use this new sync timer  --  missing?

3. the rx reader should use this new timer function - missing?

**Comment by mateumann** [comment]
@hhaim I greatly appreciate your insight.  Thanks!  Yesterdays commit was a (fastest/easiest) way to synchronize work with my colleagues, it is just a scratch I will continue working on today.

**Comment by hhaim** [comment]
I didn't look into how the algorithm works yet, but consider this:

1. high_res_tick is synced between the cores (hardware) maybe it is better to make one core (RX) responsibilities to sync the timer with remote  and maintain a **another** share  uint64 counter that call cores can read 

2. The DP scheduler works only when there is traffic is on so the algorithm will have a restart issue (I assume it should work all the timer). Maybe it would be better to have an explicit RPC command to the Rx to enable this this (Rx will work 100% of the time once you start it) -- this is diff from what you did 

3. The API for reading the counter should have two API versions
 a. read_sync_couner() uint64 : with diff (for sender - latency stream on the packet)
 b. diff_sync_couner(syncd1,syncd2) double usec for Rx side that calculate the diff between two uint64 (sync counters)

**Comment by mateumann** [comment]
@hhaim We are preparing a general purpose “scaffolding”, possibly for different synchronization algorithms.  But the first one is definitely going to be PTP working on a PTP-supporting hardware (e.g. some Intel NICs).  I guess we will end up using something different than high_res_ticks in our latency streams, probably that would be a RTC from NIC (right now we are testing system RTC with this nanoseconds patch 3c1b2b5582b6d1df1a4f6b72a31226959536858f).

However since this PR is an attempt to prepare a general purpose scaffolding with easily plugable different time synchronization mechanisms, I will try to make it so.

**Comment by mateumann** [comment]
After some internal discussion we have decided to finalize work on this (scaffolding) PR.  We will continue working on PTP time synchronization in coming PRs:
- provide a `get_time`/`set_time` interface probably somewhere around `CVirtualIF` (it seems to represent a NIC port and there could be one clock per port in PTP-supporting NICs)
- use this interface in latency streams to timestamp packets and calculate the latency
- investigate a restart issue @hhaim mentioned

**Comment by hhaim** [comment]
@mateumann as long as you will not impact the normal operation (with this feature turn off) there is no problem. 
I would start with a full software solution **without** the NIC 
* Each NIC has different limitations of the packet format  
* Reading the clock from the NIC is super slow
* In the Cloud (Amazon/Azure) the interfaces does not have this HW support 

This support (NIC PTP) should be added to the driver API first and then to the ```CVirtualIF```

**Comment by mateumann** [comment]
@hhaim thanks again!

> I would start with a full software solution **without** the NIC

Our decision exactly!  After another internal discussion, this is what we have agreed to go after first.

> Reading the clock from the NIC is super slow

Actually this was the very question I was asking myself.  I am hoping to investigate it with the physical NICs in a few weeks.  Thanks for the tip.

> In the Cloud (Amazon/Azure) the interfaces does not have this HW support.

I found a [AWS User Guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sriov-networking.html) that made me think there might be a way.  Of course I do not assume all switches and routers “in the Cloud” will support PTP but since they could (maybe one day…) we will try building something ready for this to happen.

> This support (NIC PTP) should be added to the driver API first and then to the `CVirtualIF`

As far as I know there is already some support for PTP in DPDK.  I did not have chance to investigate it yet, but would not this solve the driver API issue?

**Review by MehTheHedgehog — APPROVED** [review]

**Pull request merged**
